name: Elemental gem test suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: ['3.1', '3.0', '2.7', '2.6', '2.5']
      - name: Install dependencies
        run: bundle install
      - name: Run specs
        run: bundle exec rake
